name: Back Actions
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches: 
      - dev
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: |
          sudo apt-get install -y zip unzip
          npm install claudia -g
          npm install typescript@latest -g
          ./build.sh
      
      - name: Deploy
        uses: tkt-actions/aws-sam-cli@v1
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: |
          export "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          export "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}"
          sed "s:DB_NAME:/cosmos/${GITHUB_REF##*/}/dynamodb/table/cicd-webapp-table-user/id:g; s:USER_POOL_ARN:/cosmos/${GITHUB_REF##*/}/cognito/client/userpool/arn:g" parameters.properties.template > parameters.properties
          ./deploy.sh aws-webapp-back-${GITHUB_REF##*/} ${S3_BUCKET}